id: I84FCAC78
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T19:31:15+00:00'
last_modified: '2022-06-09T05:35:03.918803+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1174
  title: གསུང་འབུམ། བློ་བཟང་ཡེ་ཤེས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B414:
      image_group_id: I1791
      title: ''
      total_pages: 806
      order: 1
      base_file: B414.txt
    '0341':
      image_group_id: I1792
      title: ''
      total_pages: 818
      order: 2
      base_file: 0341.txt
    99D1:
      image_group_id: I1793
      title: ''
      total_pages: 918
      order: 3
      base_file: 99D1.txt
    '3365':
      image_group_id: I1794
      title: ''
      total_pages: 962
      order: 4
      base_file: 3365.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
