id: I84FCAC78
legacy_id: P007113
ocr_import_info:
  bdrc_scan_id: W1174
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T19:24:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:25:31.917358+00:00'
last_modified: 2022-08-30 22:31:04.150931
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1174
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1174
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་ཡེ་ཤེས།
  author: བློ་བཟང་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.6007774756330051
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I1794:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1794
      total_pages: 962
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1794.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6381952303900322
    legacy_id: v004
  I1792:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1792
      total_pages: 818
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1792.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.5629882240381038
    legacy_id: v002
  I1791:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1791
      total_pages: 806
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1791.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5415044832160445
    legacy_id: v001
  I1793:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1793
      total_pages: 918
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1793.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6448367631103448
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
