id: P007113
initial_creation_type: ocr
source_metadata:
  id: bdr:W1174
  title: གསུང་འབུམ། བློ་བཟང་ཡེ་ཤེས
  author: ''
  volumes:
    1c4a18169ed549cebcbf445a93418a6f:
      image_group_id: I1791
      title: ''
      volume_number: 1
      total_pages: 806
      base_file: v001.txt
    7eec586028c64a948267da1183891b7f:
      image_group_id: I1792
      title: ''
      volume_number: 2
      total_pages: 818
      base_file: v002.txt
    ebf0051b5e2e4ae191039c189c8d7d5b:
      image_group_id: I1793
      title: ''
      volume_number: 3
      total_pages: 918
      base_file: v003.txt
    cff7d545548549cd8061e175d99da08b:
      image_group_id: I1794
      title: ''
      volume_number: 4
      total_pages: 962
      base_file: v004.txt
ebook_metadata:
  title: གསུང་འབུམ། བློ་བཟང་ཡེ་ཤེས
  author: ''
  sku: P007113
  cover: cover.jpg
  layers:
  - pagination
